### ISSUE TITLE
linux报错

### ISSUE THREAD

**Issue by wzasxm** [MountCloud/FireKylin#3]

**Comment by wzasxm** [comment]
![image](https://user-images.githubusercontent.com/52563608/129011070-b661ea1e-2719-4559-93fe-ea56b72d1b8f.png)

**Comment by MountCloud** [comment]
问题已收到，这个问题的后续的修复进度将在这个issue中跟进。

**Comment by MountCloud** [comment]
感谢wzasxm反馈这个问题，此问题已在V1.1.2中已经修复。
https://github.com/MountCloud/FireKylin/releases/tag/v1.1.2
