### ISSUE TITLE
网络 IP显示问题

### ISSUE THREAD

**Issue by 2522595153** [MountCloud/FireKylin#5]
网络远程地址IP显示不对 只显示45.56.0.0 而不是45.56.23.25

**Comment by MountCloud** [comment]
> 网络远程地址IP显示不对 只显示45.56.0.0 而不是45.56.23.25

请您提供一下以下信息：1：是采集的windows平台还是linux平台以及版本，2：使用的版本，3：方便的话加一下qq群给群主发一下fkld文件。

**Comment by EriiDuck** [comment]
出现了相同问题。1.Windows10 20H1。2.软件版本为13.1。3.方便提供下群号？code中的337571436未能查到。

**Comment by MountCloud** [comment]
> 出现了相同问题。1.Windows10 20H1。2.软件版本为13.1。3.方便提供下群号？code中的337571436未能查到。

QQ群搜索仿佛被关闭了，现在可以正常搜索了。

**Comment by MountCloud** [comment]
我这也复现出来了

**Comment by MountCloud** [comment]
这个问题在v1.3.3中修复了。

**Comment by MountCloud** [comment]
感谢两位

**Comment by MountCloud** [comment]
这个issue我关闭了，如果发现未解决请重新打开。
