### ISSUE TITLE
建议增加启动项信息和计划任务信息

### ISSUE THREAD

**Issue by zhongjiao01** [MountCloud/FireKylin#7]

**Comment by MountCloud** [comment]
现在也是有详情的，请参考下面两图，如果与预期的不一样，请回复：

计划任务：
![6cfbe37338a88a66296fe11d910a86e](https://user-images.githubusercontent.com/19907386/133536494-d05c4d60-ed48-4b80-b179-166983faee51.png)
启动项：
![e875a1ea87df29ccef3618583d22ca6](https://user-images.githubusercontent.com/19907386/133536507-6a74dadd-c464-43a9-8152-4596df6cf417.png)

**Comment by MountCloud** [comment]
这个issue先关闭了，如果未得到解决再重新打开。
